### ISSUE TITLE
Morning-Session Code Review

### ISSUE THREAD

**Issue by leonardodiasb** [the-catalystmc/microverse-portfolio-setup#5]

**Comment by GuilhermeGiachellin** [comment]
Good code, I liked the way that you structured it. Congrats!

**Comment by JbirdL86** [comment]
I think your Html code is well structured and it surely works great, however, accessibility is very important for screen readers. Screen readers use HTML tags to know where does a new article or section starts or ends. Adding <article> tags can help users move around the page without seeing it. Great job!

**Comment by leonardodiasb** [comment]
Nice that you had already linked your social media links to the social icons.

Nice that you added the text content and image of the desktop version inside the works section and not created an entirely new work section for the desktop version.

You created a qualification section inside the about-me section, maybe a div tag would be more appropriate for this.
